import mysql from "mysql2/promise";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, "../.env.local") });
const conn = await mysql.createConnection({ uri: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const [rows] = await conn.execute("SELECT id, imagenUrl FROM productos WHERE imagenUrl IS NOT NULL AND imagenUrl != '' LIMIT 5");
rows.forEach(r => console.log("ID " + r.id + ": " + r.imagenUrl));
await conn.end();
